name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --immutable --immutable-cache
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      # - run: yarn install --immutable --immutable-cache
      # - run: yarn run build
      # - run: npm run test

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --include=".next"
          path: ./*
          remote_path: /home/ec2-user/langara-app
          remote_host: ec2-3-97-248-209.ca-central-1.compute.amazonaws.com
          remote_user: ec2-user
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
